# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EazyMoney' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EazyMoney
  pod "Alamofire"
  pod "SVProgressHUD"
  pod "SwiftyJSON"
  pod "CDAlertView"
  pod "SAConfettiView"
  pod 'Plaid'

end
